[package]
name = "decachedmem"
version = "0.1.0"
authors = ["Sam Phippen <samphippen@googlemail.com>"]

[dependencies]
tokio-core = { git = "https://github.com/tokio-rs/tokio-core/" }
futures = "0.1"
env_logger = "0.3.4"

[profile.release]
lto = true
