[package]
name = "decachedmem"
version = "0.1.0"
authors = ["Sam Phippen <samphippen@googlemail.com>"]
license = "MIT"

[dependencies]
futures = "0.1"
tokio-core = "0.1"
tokio-service = "0.1"
tokio-proto = "0.1"
